language: java
#jdk:
#   - oraclejdk7	#xtext 2.11 requires jdk8
#   - oraclejdk8
install: true
before_script:
   - apt-get install xvfb
   - export DISPLAY=:99.0
   #- sh -e /etc/init.d/xvfb start
   - systemctl start xvfb
   - sleep 3
script:
  - mvn clean install
after_failure:
  - cat tests/org.jnario.tests/target/work/data/.metadata/.log
